version: '2'
services:
    configuredevices-app:
        image: configuredevices
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://configuredevices-mysql:3306/configuredevices?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    configuredevices-mysql:
        extends:
            file: mysql.yml
            service: configuredevices-mysql
